/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LangIndexRouteImport } from './routes/$lang/index'
import { Route as LangServicesRouteImport } from './routes/$lang/services'
import { Route as LangPrivacyRouteImport } from './routes/$lang/privacy'
import { Route as LangIndustriesRouteImport } from './routes/$lang/industries'
import { Route as LangContactRouteImport } from './routes/$lang/contact'
import { Route as LangAboutRouteImport } from './routes/$lang/about'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LangIndexRoute = LangIndexRouteImport.update({
  id: '/$lang/',
  path: '/$lang/',
  getParentRoute: () => rootRouteImport,
} as any)
const LangServicesRoute = LangServicesRouteImport.update({
  id: '/$lang/services',
  path: '/$lang/services',
  getParentRoute: () => rootRouteImport,
} as any)
const LangPrivacyRoute = LangPrivacyRouteImport.update({
  id: '/$lang/privacy',
  path: '/$lang/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LangIndustriesRoute = LangIndustriesRouteImport.update({
  id: '/$lang/industries',
  path: '/$lang/industries',
  getParentRoute: () => rootRouteImport,
} as any)
const LangContactRoute = LangContactRouteImport.update({
  id: '/$lang/contact',
  path: '/$lang/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const LangAboutRoute = LangAboutRouteImport.update({
  id: '/$lang/about',
  path: '/$lang/about',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$lang/about': typeof LangAboutRoute
  '/$lang/contact': typeof LangContactRoute
  '/$lang/industries': typeof LangIndustriesRoute
  '/$lang/privacy': typeof LangPrivacyRoute
  '/$lang/services': typeof LangServicesRoute
  '/$lang/': typeof LangIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$lang/about': typeof LangAboutRoute
  '/$lang/contact': typeof LangContactRoute
  '/$lang/industries': typeof LangIndustriesRoute
  '/$lang/privacy': typeof LangPrivacyRoute
  '/$lang/services': typeof LangServicesRoute
  '/$lang': typeof LangIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$lang/about': typeof LangAboutRoute
  '/$lang/contact': typeof LangContactRoute
  '/$lang/industries': typeof LangIndustriesRoute
  '/$lang/privacy': typeof LangPrivacyRoute
  '/$lang/services': typeof LangServicesRoute
  '/$lang/': typeof LangIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$lang/about'
    | '/$lang/contact'
    | '/$lang/industries'
    | '/$lang/privacy'
    | '/$lang/services'
    | '/$lang/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$lang/about'
    | '/$lang/contact'
    | '/$lang/industries'
    | '/$lang/privacy'
    | '/$lang/services'
    | '/$lang'
  id:
    | '__root__'
    | '/'
    | '/$lang/about'
    | '/$lang/contact'
    | '/$lang/industries'
    | '/$lang/privacy'
    | '/$lang/services'
    | '/$lang/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LangAboutRoute: typeof LangAboutRoute
  LangContactRoute: typeof LangContactRoute
  LangIndustriesRoute: typeof LangIndustriesRoute
  LangPrivacyRoute: typeof LangPrivacyRoute
  LangServicesRoute: typeof LangServicesRoute
  LangIndexRoute: typeof LangIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang/': {
      id: '/$lang/'
      path: '/$lang'
      fullPath: '/$lang/'
      preLoaderRoute: typeof LangIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang/services': {
      id: '/$lang/services'
      path: '/$lang/services'
      fullPath: '/$lang/services'
      preLoaderRoute: typeof LangServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang/privacy': {
      id: '/$lang/privacy'
      path: '/$lang/privacy'
      fullPath: '/$lang/privacy'
      preLoaderRoute: typeof LangPrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang/industries': {
      id: '/$lang/industries'
      path: '/$lang/industries'
      fullPath: '/$lang/industries'
      preLoaderRoute: typeof LangIndustriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang/contact': {
      id: '/$lang/contact'
      path: '/$lang/contact'
      fullPath: '/$lang/contact'
      preLoaderRoute: typeof LangContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang/about': {
      id: '/$lang/about'
      path: '/$lang/about'
      fullPath: '/$lang/about'
      preLoaderRoute: typeof LangAboutRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LangAboutRoute: LangAboutRoute,
  LangContactRoute: LangContactRoute,
  LangIndustriesRoute: LangIndustriesRoute,
  LangPrivacyRoute: LangPrivacyRoute,
  LangServicesRoute: LangServicesRoute,
  LangIndexRoute: LangIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
